spring:
  security.oauth2.client:
    registration:
      google:
        client-id: ENTER_YOUR_OAUTH_PROVIDER_CLIENT_ID
        client-secret: ENTER_YOUR_OAUTH_PROVIDER_CLIENT_KEY
      github:
        client-id:  ENTER_YOUR_OAUTH_PROVIDER_CLIENT_ID
        client-secret: ENTER_YOUR_OAUTH_PROVIDER_CLIENT_KEY